name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed successfully."

      - name: Start Node.js Server
        run: |
          echo "Starting Node.js server..."
          npm start &
          echo "Node.js server started successfully."

      - name: Wait for Server to Start
        run: sleep 5  # Adjust sleep time if needed

      - name: Deploy Using ngrok
        run: |
          echo "Deploying using ngrok..."
          ngrok http http://localhost:5500
